apiVersion: v1
name: techtrends
keywords:
  - techtrends
version: 1.0.0
maintainers:
  - name: Johan MÃ¸ller
    email: johan@johans.dk
description: A Helm chart for deploying the TechTrends application
